version: '3.8'

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d api.lexy-docs.com -d app.lexy-docs.com --force-renewal

  django_gunicorn:
    build:
      context: ./lexyapi/src
    env_file:
      - ./lexyapi/src/project/.env
    ports:
      - "8000:8000"
    volumes:
      - static:/static

  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
      - ./lexydocs/dist:/usr/share/nginx/html/frontend1
    depends_on:
      - django_gunicorn

volumes:
  static: